runtime: python39
entrypoint: gunicorn -b :8080 main:app

env_variables:
  DB_URL: "postgresql://postgres:escrow@34.93.201.117:5432/postgres"
  SECRET: "3f4e1462c7bda198adf757f33f354e45672333c29613c645"

handlers:
- url: /.*
  script: auto
